### PR TITLE
fix proxy implementation and rename variable

### PR DESCRIPTION
**Pull request by kumarrishav**

### CODE REVIEW

**Review by mitchellalderson — APPROVED** [review]

**Comment by mitchellalderson** [comment]
@kumarrishav can you write a test case for this when you get a chance? We can do it in another PR.

**Comment by kumarrishav** [comment]
sure. I wasn't expecting the PR merge as you might not find it ts-fied. 

Thanks for the merge. will send PR

**Comment by mitchellalderson** [comment]
@kumarrishav I had to revert, there are some problems with the implementation that we didn't see when doing the tunnel after the fact. I'll add you to the new PR.

**Comment by kumarrishav** [comment]
yeah. issue while doing the import

**Comment by kumarrishav** [comment]
https://github.com/farawaysouthwest/axios-proxy-builder/pull/3

you can close this one then

that's what i was afraid of - i don't use import normally and obvious ts.

**Pull request merged**
